-- Clean ERP test tables
DELETE FROM erp_stock_record;
DELETE FROM erp_stock;
DELETE FROM erp_stock_location;
DELETE FROM erp_stock_batch;
DELETE FROM erp_stock_in_item;
DELETE FROM erp_stock_in;
DELETE FROM erp_stock_out_item;
DELETE FROM erp_stock_out;
DELETE FROM erp_stock_move_item;
DELETE FROM erp_stock_move;
DELETE FROM erp_stock_check_item;
DELETE FROM erp_stock_check;
DELETE FROM erp_warehouse;
DELETE FROM erp_supplier;
DELETE FROM erp_customer;
DELETE FROM erp_purchase_order;
DELETE FROM erp_purchase_in;
DELETE FROM erp_purchase_return;
