-- 工行反向开票订单表
CREATE TABLE `icbc_invoice_order` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `order_no` varchar(64) NOT NULL COMMENT '订单号（我方生成）',
  `partner_order_id` varchar(35) NOT NULL COMMENT '合作方订单ID（传给工行）',
  `acquisition_id` bigint DEFAULT NULL COMMENT '来源收购单编号（一个收购单对应一张票）',
  `payee_id` bigint DEFAULT NULL COMMENT '收方ID',
  `payee_no` varchar(40) NOT NULL COMMENT '收方编号',
  `payer_id` bigint DEFAULT NULL COMMENT '付方ID',
  `payer_no` varchar(20) NOT NULL COMMENT '付方编号',
  `total_amount` decimal(14,2) NOT NULL COMMENT '订单总金额（元）',
  `tax_rate` decimal(5,4) DEFAULT NULL COMMENT '适用征收率（0.01=3%减按1%，0.03=放弃减按）',
  `invoice_type` tinyint NOT NULL DEFAULT '1' COMMENT '发票类型：1-增值税普通发票，2-增值税专用发票',
  `business_type` varchar(20) NOT NULL COMMENT '业务类型：AGRICULTURAL-农产品收购，SCRAP-报废产品收购',
  `order_status` tinyint NOT NULL DEFAULT '0' COMMENT '订单状态：0-待确认，1-已确认，2-已支付，3-已开票，4-已完成，9-已取消',
  `invoice_status` tinyint NOT NULL DEFAULT '0' COMMENT '开票状态：0-未开票，1-开票中，2-已开票，3-开票失败',
  `payment_status` tinyint NOT NULL DEFAULT '0' COMMENT '支付状态：0-未支付，1-支付中，2-支付成功，3-支付失败',
  `tax_status` tinyint NOT NULL DEFAULT '0' COMMENT '缴税状态：0-未缴税，1-缴税中，2-缴税成功，3-缴税失败，4-异常（金额不一致），5-异常（未知），6-无需缴税',
  `upload_status` tinyint DEFAULT NULL COMMENT '发票上传状态：0-未上传，1-处理中，2-已受理，3-上传中，4-上传成功，5-上传失败',
  `tax_real_amount` decimal(14,2) DEFAULT NULL COMMENT '实缴税额（工行 taxRealAmount）',
  `tax_time` datetime DEFAULT NULL COMMENT '缴税时间（工行 tradeTime）',
  `tax_payment_method` varchar(4) DEFAULT NULL COMMENT '税费缴纳方式：0-自然人自行办理，1-企业委托扣缴',
  `tax_voucher_no` varchar(64) DEFAULT NULL COMMENT '应征凭证序号（缴税凭证编号）',
  `confirm_status` tinyint NOT NULL DEFAULT '0' COMMENT '自然人确认状态：0-未确认，1-自然人确认完成，2-全部确认完成',
  `pre_invoice_status` tinyint NOT NULL DEFAULT '0' COMMENT '预开票状态：0-初始，1-预开票中，2-预开票成功，3-预开票失败，4-预开票取消',
  `pre_order_time` datetime DEFAULT NULL COMMENT '预下单发起时间',
  `invoice_no` varchar(20) DEFAULT NULL COMMENT '发票号码',
  `invoice_code` varchar(20) DEFAULT NULL COMMENT '发票代码',
  `invoice_date` datetime DEFAULT NULL COMMENT '开票日期',
  `invoice_amount` decimal(14,2) DEFAULT NULL COMMENT '发票金额',
  `tax_amount` decimal(14,2) DEFAULT NULL COMMENT '税额',
  `invoice_file_url` varchar(500) DEFAULT NULL COMMENT '发票文件URL',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_no` (`order_no`),
  UNIQUE KEY `uk_partner_order_id` (`partner_order_id`),
  KEY `idx_acquisition_id` (`acquisition_id`),
  KEY `idx_payee_no` (`payee_no`),
  KEY `idx_payer_no` (`payer_no`),
  KEY `idx_invoice_no` (`invoice_no`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工行反向开票订单表';

-- 出售者额度超限的经营主体登记引导表（#12）
CREATE TABLE `icbc_seller_quota_guidance` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `payee_id` bigint NOT NULL COMMENT '出售者档案编号',
  `seller_name` varchar(100) DEFAULT NULL COMMENT '出售者姓名',
  `id_card_no` varchar(32) DEFAULT NULL COMMENT '身份证号码',
  `trigger_scene` varchar(32) DEFAULT NULL COMMENT '触发场景：INVOICE_APPLICATION-开票申请被拒，ACQUISITION-收购登记时已超',
  `trigger_biz_no` varchar(64) DEFAULT NULL COMMENT '触发业务单号（收购单号 / 合作方订单号）',
  `used_amount` decimal(14,2) DEFAULT NULL COMMENT '触发时连续 12 个月累计已用额度（元）',
  `cap_amount` decimal(14,2) DEFAULT NULL COMMENT '触发时窗口上限（元），500 万',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '引导状态：0-待引导，1-已引导，2-已办结',
  `triggered_at` datetime DEFAULT NULL COMMENT '首次触发时间',
  `last_triggered_at` datetime DEFAULT NULL COMMENT '最近一次触发时间',
  `handled_at` datetime DEFAULT NULL COMMENT '处理时间',
  `handle_remark` varchar(500) DEFAULT NULL COMMENT '处理说明',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_quota_guidance_payee_id` (`payee_id`),
  KEY `idx_quota_guidance_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='出售者额度超限的经营主体登记引导表';

CREATE TABLE `icbc_tax_declaration` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `declaration_no` varchar(64) DEFAULT NULL COMMENT '申报单号',
  `period_month` varchar(7) NOT NULL COMMENT '申报月 yyyy-MM',
  `declaration_deadline` date DEFAULT NULL COMMENT '申报期截止日（次月 15 日）',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '状态：0-待申报，1-已申报待缴款，2-已缴款',
  `seller_count` int DEFAULT NULL COMMENT '涉及出售者数',
  `over_exempt_seller_count` int DEFAULT NULL COMMENT '当月销售额超 10 万元、需单独列出的出售者数',
  `total_sales_amount` decimal(14,2) DEFAULT NULL COMMENT '当月净销售额合计（元）',
  `amount_at_one_percent` decimal(14,2) DEFAULT NULL COMMENT '按 3% 减按 1% 的销售额（元）',
  `amount_at_three_percent` decimal(14,2) DEFAULT NULL COMMENT '放弃减按、按 3% 的销售额（元）',
  `other_amount` decimal(14,2) DEFAULT NULL COMMENT '征收率未识别的销售额（元）',
  `vat_amount` decimal(14,2) DEFAULT NULL COMMENT '应缴增值税合计（元）',
  `surcharge_amount` decimal(14,2) DEFAULT NULL COMMENT '应缴附加税费合计（元）',
  `iit_amount` decimal(14,2) DEFAULT NULL COMMENT '应缴个人所得税合计（元）',
  `total_tax_amount` decimal(14,2) DEFAULT NULL COMMENT '应缴税费合计（元）',
  `paid_amount` decimal(14,2) DEFAULT NULL COMMENT '实缴金额（元）',
  `declared_at` datetime DEFAULT NULL COMMENT '申报时间',
  `declared_by` varchar(64) DEFAULT NULL COMMENT '申报人',
  `declared_remark` varchar(500) DEFAULT NULL COMMENT '申报备注',
  `paid_at` datetime DEFAULT NULL COMMENT '缴款时间',
  `payment_method` varchar(64) DEFAULT NULL COMMENT '缴纳方式',
  `voucher_no` varchar(64) DEFAULT NULL COMMENT '缴款凭证号',
  `voucher_file_url` varchar(500) DEFAULT NULL COMMENT '缴款凭证文件地址',
  `data_ready` bit(1) DEFAULT b'1' COMMENT '申报数据是否齐备',
  `missing_data_count` int DEFAULT NULL COMMENT '缺项数量',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_tax_declaration_period` (`tenant_id`, `period_month`),
  KEY `idx_tax_declaration_deadline` (`declaration_deadline`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='代办税费申报单（#13）';

CREATE TABLE `icbc_tax_declaration_item` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `declaration_id` bigint DEFAULT NULL COMMENT '申报单编号',
  `period_month` varchar(7) DEFAULT NULL COMMENT '申报月 yyyy-MM',
  `payee_id` bigint DEFAULT NULL COMMENT '出售者档案编号',
  `seller_name` varchar(100) DEFAULT NULL COMMENT '出售者姓名',
  `id_card_no` varchar(32) DEFAULT NULL COMMENT '身份证号码',
  `invoice_count` int DEFAULT NULL COMMENT '当月本租户开票张数',
  `sales_amount` decimal(14,2) DEFAULT NULL COMMENT '当月本租户净销售额（元）',
  `amount_at_one_percent` decimal(14,2) DEFAULT NULL COMMENT '按 3% 减按 1% 的销售额（元）',
  `amount_at_three_percent` decimal(14,2) DEFAULT NULL COMMENT '放弃减按、按 3% 的销售额（元）',
  `other_amount` decimal(14,2) DEFAULT NULL COMMENT '征收率未识别的销售额（元）',
  `cross_tenant_month_amount` decimal(14,2) DEFAULT NULL COMMENT '该自然人当月在平台各租户的净销售额合计（10 万元免征线口径）',
  `vat_exempt` bit(1) DEFAULT NULL COMMENT '增值税是否免征（未超 10 万元）',
  `over_exempt` bit(1) DEFAULT NULL COMMENT '当月销售额（跨租户）是否超 10 万元',
  `vat_amount` decimal(14,2) DEFAULT NULL COMMENT '应缴增值税（元）',
  `surcharge_amount` decimal(14,2) DEFAULT NULL COMMENT '应缴附加税费（元）',
  `iit_amount` decimal(14,2) DEFAULT NULL COMMENT '应缴个人所得税（元）',
  `total_tax_amount` decimal(14,2) DEFAULT NULL COMMENT '应缴税费合计（元）',
  `paid_amount` decimal(14,2) DEFAULT NULL COMMENT '实缴金额（元）',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '状态，同申报单状态线',
  `paid_at` datetime DEFAULT NULL COMMENT '缴款时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_tax_item_declaration` (`declaration_id`),
  KEY `idx_tax_item_payee` (`payee_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='代办税费申报明细（#13）';

CREATE TABLE `icbc_tax_declaration_invoice` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `declaration_id` bigint DEFAULT NULL COMMENT '申报单编号',
  `period_month` varchar(7) DEFAULT NULL COMMENT '申报月 yyyy-MM',
  `invoice_order_id` bigint DEFAULT NULL COMMENT '开票订单编号',
  `partner_order_id` varchar(64) DEFAULT NULL COMMENT '合作方订单号',
  `invoice_no` varchar(64) DEFAULT NULL COMMENT '发票号码',
  `payee_id` bigint DEFAULT NULL COMMENT '出售者档案编号',
  `direction` varchar(8) DEFAULT NULL COMMENT '方向：BLUE-蓝票计入，RED-红票冲减',
  `amount` decimal(14,2) DEFAULT NULL COMMENT '金额（元）',
  `tax_rate` decimal(5,4) DEFAULT NULL COMMENT '适用征收率',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_tax_invoice_declaration` (`declaration_id`),
  KEY `idx_tax_invoice_order` (`invoice_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='申报单与发票关联（#13）';

CREATE TABLE `icbc_tax_supplement` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `supplement_no` varchar(64) DEFAULT NULL COMMENT '补缴单号',
  `declaration_id` bigint DEFAULT NULL COMMENT '关联申报单编号',
  `period_month` varchar(7) DEFAULT NULL COMMENT '所属申报月 yyyy-MM',
  `payee_id` bigint DEFAULT NULL COMMENT '出售者档案编号',
  `seller_name` varchar(100) DEFAULT NULL COMMENT '出售者姓名',
  `reason` varchar(500) DEFAULT NULL COMMENT '补缴原因',
  `amount_at_one_percent` decimal(14,2) DEFAULT NULL COMMENT '按 3% 减按 1% 部分的补缴金额（元）',
  `amount_at_three_percent` decimal(14,2) DEFAULT NULL COMMENT '放弃减按、按 3% 部分的补缴金额（元）',
  `amount` decimal(14,2) DEFAULT NULL COMMENT '应补缴金额合计（元）',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '状态：0-待补缴，1-已补缴',
  `paid_amount` decimal(14,2) DEFAULT NULL COMMENT '实缴金额（元）',
  `paid_at` datetime DEFAULT NULL COMMENT '缴款时间',
  `voucher_no` varchar(64) DEFAULT NULL COMMENT '缴款凭证号',
  `voucher_file_url` varchar(500) DEFAULT NULL COMMENT '缴款凭证文件地址',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_tax_supplement_declaration` (`declaration_id`),
  KEY `idx_tax_supplement_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='需补缴税费（#13）';

CREATE TABLE `icbc_settlement_reminder` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `payee_id` bigint DEFAULT NULL COMMENT '出售者档案编号',
  `seller_name` varchar(100) DEFAULT NULL COMMENT '出售者姓名',
  `id_card_no` varchar(32) DEFAULT NULL COMMENT '身份证号码',
  `tax_year` int DEFAULT NULL COMMENT '纳税年度',
  `deadline` date DEFAULT NULL COMMENT '汇算清缴截止日（次年 3 月 31 日）',
  `invoice_count` int DEFAULT NULL COMMENT '当年开票张数',
  `invoiced_amount` decimal(14,2) DEFAULT NULL COMMENT '当年开票金额（元）',
  `paid_tax_amount` decimal(14,2) DEFAULT NULL COMMENT '当年已预缴税费合计（元）',
  `iit_amount` decimal(14,2) DEFAULT NULL COMMENT '当年已预缴个人所得税（元）',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '状态：0-待提醒，1-已提醒',
  `reminded_at` datetime DEFAULT NULL COMMENT '提醒时间',
  `handle_remark` varchar(500) DEFAULT NULL COMMENT '处理说明',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_settlement_reminder_payee` (`payee_id`),
  KEY `idx_settlement_reminder_tax_year` (`tax_year`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='出售者汇算清缴提醒（#13）';

-- 工行订单商品明细表
CREATE TABLE `icbc_order_item` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `order_id` bigint NOT NULL COMMENT '订单ID',
  `order_no` varchar(64) NOT NULL COMMENT '订单号',
  `item_name` varchar(300) NOT NULL COMMENT '商品名称',
  `item_code` varchar(50) DEFAULT NULL COMMENT '商品编码',
  `specification` varchar(100) DEFAULT NULL COMMENT '规格型号',
  `unit` varchar(10) NOT NULL COMMENT '单位',
  `quantity` decimal(14,4) NOT NULL COMMENT '数量',
  `unit_price` decimal(14,2) NOT NULL COMMENT '单价（元）',
  `amount` decimal(14,2) NOT NULL COMMENT '金额（元）',
  `tax_rate` decimal(4,2) NOT NULL COMMENT '税率',
  `tax_amount` decimal(14,2) DEFAULT NULL COMMENT '税额（元）',
  `quantity_note` varchar(200) DEFAULT NULL COMMENT '数量口径说明（结算重量计价后发票数量与磅单净重的差异）',
  `category` varchar(50) DEFAULT NULL COMMENT '商品分类',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_order_id` (`order_id`),
  KEY `idx_order_no` (`order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工行订单商品明细表';

-- 插入菜单权限
INSERT INTO system_menu (
    name, permission, type, sort, parent_id, path, icon, component, component_name, status, visible, keep_alive, always_show, creator, create_time, updater, update_time, deleted
) VALUES (
    '工行反向开票', '', 2, 3, 2000, 'icbc-invoice', 'ep:document', 'icbc/invoice/index', 'IcbcInvoice', 0, b'1', b'1', b'1', '1', NOW(), '1', NOW(), b'0'
);

-- 获取刚插入的菜单ID
SET @menu_id = LAST_INSERT_ID();

-- 插入按钮权限
INSERT INTO system_menu (
    name, permission, type, sort, parent_id, path, icon, component, component_name, status, visible, keep_alive, always_show, creator, create_time, updater, update_time, deleted
) VALUES 
('工行反向开票创建', 'icbc:invoice-order:create', 3, 1, @menu_id, '', '', '', '', 0, b'1', b'1', b'1', '1', NOW(), '1', NOW(), b'0'),
('工行反向开票查询', 'icbc:invoice-order:query', 3, 2, @menu_id, '', '', '', '', 0, b'1', b'1', b'1', '1', NOW(), '1', NOW(), b'0'),
('工行反向开票更新', 'icbc:invoice-order:update', 3, 3, @menu_id, '', '', '', '', 0, b'1', b'1', b'1', '1', NOW(), '1', NOW(), b'0'),
('工行反向开票删除', 'icbc:invoice-order:delete', 3, 4, @menu_id, '', '', '', '', 0, b'1', b'1', b'1', '1', NOW(), '1', NOW(), b'0'); 