-- ========================================
-- 收购登记（#7）：一笔收购的合同流 / 货物流 / 信息流骨架
-- 幂等：CREATE TABLE IF NOT EXISTS
-- ========================================

CREATE TABLE IF NOT EXISTS `icbc_acquisition` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `acquisition_no` varchar(64) NOT NULL COMMENT '收购单号（合同编号）',
  `client_request_id` varchar(64) DEFAULT NULL COMMENT '客户端幂等键（离线补传去重）',
  `payee_id` bigint unsigned NOT NULL COMMENT '出售者（收方）档案编号',
  `partner_payee_id` varchar(64) DEFAULT NULL COMMENT '出售者外部编号快照',
  `seller_name` varchar(100) DEFAULT NULL COMMENT '出售者姓名快照',
  `seller_mobile` varchar(32) DEFAULT NULL COMMENT '出售者联系方式快照',
  `goods_config_id` bigint unsigned DEFAULT NULL COMMENT '品类配置编号',
  `category_name` varchar(100) DEFAULT NULL COMMENT '品类名称',
  `unit` varchar(20) DEFAULT NULL COMMENT '计量单位（按品类带出）',
  `tax_rate` decimal(5,4) DEFAULT NULL COMMENT '税率（按品类带出）',
  `tax_method` varchar(20) DEFAULT NULL COMMENT '计税方法：SIMPLE/GENERAL（按品类带出）',
  `merged_code` varchar(19) DEFAULT NULL COMMENT '商品和服务税收分类合并编码（按品类带出）',
  `specification` varchar(100) DEFAULT NULL COMMENT '规格',
  `quantity` decimal(14,4) DEFAULT NULL COMMENT '数量',
  `unit_price` decimal(14,2) DEFAULT NULL COMMENT '含税单价（元）',
  `amount` decimal(14,2) DEFAULT NULL COMMENT '金额（元）',
  `gross_weight` decimal(14,4) DEFAULT NULL COMMENT '毛重',
  `tare_weight` decimal(14,4) DEFAULT NULL COMMENT '皮重',
  `net_weight` decimal(14,4) DEFAULT NULL COMMENT '净重',
  `weight_ticket_no` varchar(64) DEFAULT NULL COMMENT '磅单号',
  `weight_ticket_image_url` varchar(500) DEFAULT NULL COMMENT '磅单照片地址',
  `weight_ticket_plate_no` varchar(32) DEFAULT NULL COMMENT '磅单识别车牌',
  `vehicle_plate_no` varchar(32) DEFAULT NULL COMMENT '车头车尾识别车牌',
  `plate_matched` tinyint(1) DEFAULT NULL COMMENT '车牌比对：1-一致，0-不一致，NULL-无法比对',
  `vehicle_front_image_url` varchar(500) DEFAULT NULL COMMENT '车头照片地址',
  `vehicle_rear_image_url` varchar(500) DEFAULT NULL COMMENT '车尾照片地址',
  `trade_address` varchar(255) DEFAULT NULL COMMENT '交易地点',
  `trade_time` datetime DEFAULT NULL COMMENT '交易时间',
  `settlement_method` varchar(200) DEFAULT NULL COMMENT '结算方式',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '状态：0-已登记，1-待付款，2-已付款，3-已开票，9-已取消',
  `invoice_partner_order_id` varchar(64) DEFAULT NULL COMMENT '关联开票合作方订单号',
  `source` varchar(20) DEFAULT NULL COMMENT '登记来源：ONLINE/OFFLINE_SYNC',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `tenant_id` bigint unsigned NOT NULL DEFAULT '0' COMMENT '租户编号',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_acquisition_no` (`acquisition_no`),
  UNIQUE KEY `uk_acquisition_client_request` (`tenant_id`, `client_request_id`),
  KEY `idx_acquisition_payee_id` (`payee_id`),
  KEY `idx_acquisition_invoice_order` (`invoice_partner_order_id`),
  KEY `idx_acquisition_trade_time` (`trade_time`),
  KEY `idx_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='收购登记单';
