<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>cn.iocoder.boot</groupId>
        <artifactId>yudao</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <modules>
        <module>yudao-module-pay-enterprise-api</module>
        <module>yudao-module-pay-enterprise-biz</module>
    </modules>
    <artifactId>yudao-module-pay-enterprise</artifactId>
    <packaging>pom</packaging>

    <name>${project.artifactId}</name>
    <description>
        企业付款模块，负责企业间付款和结算管理，包括付款账户管理、付款申请、付款审批、付款执行、对账管理等功能
    </description>
</project> 