<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>cn.iocoder.boot</groupId>
        <artifactId>yudao</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <modules>
        <module>yudao-module-logistics-api</module>
        <module>yudao-module-logistics-biz</module>
    </modules>
    <artifactId>yudao-module-logistics</artifactId>
    <packaging>pom</packaging>

    <name>${project.artifactId}</name>
    <description>
        物流模块，负责运输执行和操作管理中心，包括运输任务管理、运输节点跟踪、过磅操作、现金代付、资源管理等功能
    </description>
</project> 