-- 物流运输模块数据库表结构脚本（第四部分）
-- 创建日期：2024年05月

-- 创建在途量监控记录表
CREATE TABLE IF NOT EXISTS `logistics_in_transit_volume` (
  `id` bigint(20) NOT NULL COMMENT '记录ID',
  `vehicle_id` bigint(20) NOT NULL COMMENT '车辆ID',
  `vehicle_no` varchar(20) NOT NULL COMMENT '车牌号',
  `driver_id` bigint(20) NOT NULL COMMENT '司机ID',
  `driver_name` varchar(64) NOT NULL COMMENT '司机姓名',
  `waste_code` varchar(50) NOT NULL COMMENT '危险废物代码',
  `waste_name` varchar(100) NOT NULL COMMENT '危险废物名称',
  `current_volume` decimal(10,2) NOT NULL COMMENT '当前在途量',
  `unit` varchar(10) NOT NULL COMMENT '单位',
  `related_task_ids` text COMMENT '关联的任务IDs(JSON数组)',
  `task_count` int(11) NOT NULL DEFAULT '0' COMMENT '任务数量',
  `last_update_time` datetime NOT NULL COMMENT '最后更新时间',
  `last_location` varchar(500) DEFAULT '' COMMENT '最后位置',
  `last_latitude` decimal(10,7) DEFAULT NULL COMMENT '最后纬度',
  `last_longitude` decimal(10,7) DEFAULT NULL COMMENT '最后经度',
  `is_alert` bit(1) DEFAULT b'0' COMMENT '是否预警',
  `alert_type` tinyint(4) DEFAULT NULL COMMENT '预警类型',
  `alert_reason` varchar(500) DEFAULT '' COMMENT '预警原因',
  `start_time` datetime NOT NULL COMMENT '开始时间',
  `duration_hours` decimal(10,2) DEFAULT NULL COMMENT '持续时长(小时)',
  `tenant_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '租户ID',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  KEY `idx_vehicle_id` (`vehicle_id`),
  KEY `idx_driver_id` (`driver_id`),
  KEY `idx_waste_code` (`waste_code`),
  KEY `idx_last_update_time` (`last_update_time`),
  KEY `idx_is_alert` (`is_alert`),
  KEY `idx_tenant_id_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='在途量监控记录表';

-- 创建在途量变更日志表
CREATE TABLE IF NOT EXISTS `logistics_in_transit_volume_log` (
  `id` bigint(20) NOT NULL COMMENT '日志ID',
  `volume_id` bigint(20) NOT NULL COMMENT '在途量记录ID',
  `vehicle_id` bigint(20) NOT NULL COMMENT '车辆ID',
  `task_id` bigint(20) NOT NULL COMMENT '任务ID',
  `event_type` tinyint(4) NOT NULL COMMENT '事件类型(0:装货完成,1:开始卸货,2:定时上报)',
  `event_time` datetime NOT NULL COMMENT '事件时间',
  `volume_before` decimal(10,2) NOT NULL COMMENT '变更前在途量',
  `volume_change` decimal(10,2) NOT NULL COMMENT '变更量',
  `volume_after` decimal(10,2) NOT NULL COMMENT '变更后在途量',
  `node_id` bigint(20) DEFAULT NULL COMMENT '关联的节点ID',
  `location` varchar(500) DEFAULT '' COMMENT '位置',
  `latitude` decimal(10,7) DEFAULT NULL COMMENT '纬度',
  `longitude` decimal(10,7) DEFAULT NULL COMMENT '经度',
  `remark` varchar(500) DEFAULT '' COMMENT '备注',
  `tenant_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '租户ID',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  KEY `idx_volume_id` (`volume_id`),
  KEY `idx_vehicle_id` (`vehicle_id`),
  KEY `idx_task_id` (`task_id`),
  KEY `idx_event_type` (`event_type`),
  KEY `idx_event_time` (`event_time`),
  KEY `idx_tenant_id_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='在途量变更日志表';

-- 创建临时订单表
CREATE TABLE IF NOT EXISTS `logistics_temporary_order` (
  `id` bigint(20) NOT NULL COMMENT '临时订单ID',
  `order_no` varchar(64) NOT NULL COMMENT '临时订单号',
  `task_id` bigint(20) NOT NULL COMMENT '关联的运输任务ID',
  `driver_id` bigint(20) NOT NULL COMMENT '司机ID',
  `driver_name` varchar(64) NOT NULL COMMENT '司机姓名',
  `waste_type` varchar(50) NOT NULL COMMENT '废物类型代码',
  `waste_name` varchar(100) NOT NULL COMMENT '废物名称',
  `estimated_quantity` decimal(10,2) NOT NULL COMMENT '预估数量',
  `quantity_unit` varchar(10) NOT NULL COMMENT '数量单位',
  `pickup_location` varchar(500) NOT NULL COMMENT '取货地址',
  `pickup_latitude` decimal(10,7) DEFAULT NULL COMMENT '取货纬度',
  `pickup_longitude` decimal(10,7) DEFAULT NULL COMMENT '取货经度',
  `pickup_time` datetime NOT NULL COMMENT '取货时间',
  `producer_name` varchar(64) NOT NULL COMMENT '产废方姓名',
  `producer_phone` varchar(20) NOT NULL COMMENT '产废方电话',
  `producer_id_card` varchar(20) DEFAULT NULL COMMENT '产废方身份证',
  `discovery_photos` text COMMENT '现场照片URLs(JSON数组)',
  `estimated_value` decimal(10,2) DEFAULT NULL COMMENT '预估价值',
  `payment_status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '支付状态(0:未支付,1:已支付)',
  `payment_amount` decimal(10,2) DEFAULT NULL COMMENT '支付金额',
  `payment_time` datetime DEFAULT NULL COMMENT '支付时间',
  `payment_method` varchar(20) DEFAULT NULL COMMENT '支付方式',
  `payment_voucher_url` varchar(255) DEFAULT NULL COMMENT '支付凭证URL',
  `converted_to_formal` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否已转为正式订单',
  `formal_order_id` bigint(20) DEFAULT NULL COMMENT '关联的正式订单ID',
  `conversion_time` datetime DEFAULT NULL COMMENT '转换时间',
  `remark` varchar(500) DEFAULT '' COMMENT '备注',
  `tenant_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '租户ID',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_no` (`order_no`),
  KEY `idx_task_id` (`task_id`),
  KEY `idx_driver_id` (`driver_id`),
  KEY `idx_waste_type` (`waste_type`),
  KEY `idx_pickup_time` (`pickup_time`),
  KEY `idx_payment_status` (`payment_status`),
  KEY `idx_converted_to_formal` (`converted_to_formal`),
  KEY `idx_tenant_id_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='临时订单表';

-- 创建运输统计表
CREATE TABLE IF NOT EXISTS `logistics_transport_statistics` (
  `id` bigint(20) NOT NULL COMMENT '统计ID',
  `statistics_date` date NOT NULL COMMENT '统计日期',
  `statistics_type` tinyint(4) NOT NULL COMMENT '统计类型(0:日报,1:周报,2:月报)',
  `total_tasks` int(11) NOT NULL DEFAULT '0' COMMENT '总任务数',
  `completed_tasks` int(11) NOT NULL DEFAULT '0' COMMENT '已完成任务数',
  `cancelled_tasks` int(11) NOT NULL DEFAULT '0' COMMENT '已取消任务数',
  `total_volume` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT '总运输量',
  `total_distance` decimal(10,2) DEFAULT '0.00' COMMENT '总运输距离(km)',
  `average_task_duration` decimal(10,2) DEFAULT '0.00' COMMENT '平均任务时长(小时)',
  `on_time_rate` decimal(5,2) DEFAULT '0.00' COMMENT '准时率(%)',
  `abnormal_task_count` int(11) DEFAULT '0' COMMENT '异常任务数',
  `temporary_order_count` int(11) DEFAULT '0' COMMENT '临时订单数',
  `company_distribution` text COMMENT '物流公司分布(JSON)',
  `waste_type_distribution` text COMMENT '废物类型分布(JSON)',
  `vehicle_utilization_rate` decimal(5,2) DEFAULT '0.00' COMMENT '车辆利用率(%)',
  `remark` varchar(500) DEFAULT '' COMMENT '备注',
  `tenant_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '租户ID',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_statistics_date_type_tenant` (`statistics_date`, `statistics_type`, `tenant_id`),
  KEY `idx_statistics_date` (`statistics_date`),
  KEY `idx_statistics_type` (`statistics_type`),
  KEY `idx_tenant_id_deleted` (`tenant_id`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='运输统计表'; 