<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>cn.iocoder.boot</groupId>
        <artifactId>yudao</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <modules>
        <module>yudao-module-waste-api</module>
        <module>yudao-module-waste-biz</module>
    </modules>
    <artifactId>yudao-module-waste</artifactId>
    <packaging>pom</packaging>

    <name>${project.artifactId}</name>
    <description>
        危险废物转移模块，负责业务决策和交易管理中心，包括预约管理、订单管理、付款管理、过磅分摊、合同价格等功能
    </description>
</project> 