<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>cn.iocoder.boot</groupId>
        <artifactId>yudao</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <modules>
        <module>yudao-module-contract-api</module>
        <module>yudao-module-contract-biz</module>
    </modules>
    <artifactId>yudao-module-contract</artifactId>
    <packaging>pom</packaging>

    <name>${project.artifactId}</name>
    <description>
        contract 模块，负责合同管理功能，包括合同类型、模板、签署、版本管理等
    </description>
</project> 